apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-operator3
  namespace: openshift-gateway-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servicemesh-operator3
subjects:
- kind: ServiceAccount
  name: servicemesh-operator3
  namespace: openshift-gateway-api
