apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: servicemesh-operator3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicemesh-operator3
subjects:
- kind: ServiceAccount
  name: servicemesh-operator3
  namespace: openshift-gateway-api
