spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/created-by: servicemeshoperator3
      app.kubernetes.io/part-of: servicemeshoperator3
      control-plane: servicemesh-operator3
  strategy: {}
  template:
    metadata:
      annotations:
        images.v1_23_0.cni: registry.redhat.io/openshift-service-mesh-tech-preview/istio-cni-rhel9@sha256:f16cd8a29ddcbb3de77cbfcf7e1da78e42cc0c1c502132d477a01c52689cdf23
        images.v1_23_0.istiod: registry.redhat.io/openshift-service-mesh-tech-preview/istio-pilot-rhel9@sha256:376f64eab0ebeb06035983a60d1e7647c5d41354f31a49cb34f4deb7b6708e3e
        images.v1_23_0.must-gather: registry.redhat.io/openshift-service-mesh-tech-preview/istio-must-gather-rhel9@sha256:e3978aecaafe2678355e21a7303f8620f53d8b774f6592f10527c15bae957224
        images.v1_23_0.proxy: registry.redhat.io/openshift-service-mesh-tech-preview/istio-proxyv2-rhel9@sha256:cbd6bc47341ab8618609f89d063552e17232541c727429855c01deab73e4d06c
        images.v1_23_0.ztunnel: registry.redhat.io/openshift-service-mesh-tech-preview/istio-pilot-rhel9@sha256:376f64eab0ebeb06035983a60d1e7647c5d41354f31a49cb34f4deb7b6708e3e
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/created-by: servicemeshoperator3
        app.kubernetes.io/part-of: servicemeshoperator3
        control-plane: servicemesh-operator3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: kube-rbac-proxy
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --default-profile=openshift
          command:
            - /usr/local/bin/manager
          image: manager
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /etc/sail-operator
              name: operator-config
              readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: servicemesh-operator3
      terminationGracePeriodSeconds: 10
      volumes:
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  fieldPath: metadata.annotations
                path: config.properties
          name: operator-config
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-gateway-api
  name: servicemesh-operator3
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: servicemeshoperator3
    app.kubernetes.io/instance: servicemesh-operator3
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: servicemeshoperator3
    control-plane: servicemesh-operator3
